### ISSUE TITLE
Bundling library with browser-polyfill?

### ISSUE THREAD

**Issue by nicksrandall** [babel/babel-library-boilerplate#145]
I'm seeking "best practice" advice. I have built a library using this template that is intended to be used in the browser. Therefore,  I need my library to be bundled with babel's browser-polyfill for everything to work properly. What would be the best way to do that?

Has anybody been faced with a similar scenario? What did you do?

Thanks for any help!

**Comment by jmeas** [comment]
@nicksrandall, I tend to not bundle the browser polyfill with the libraries I make with this boilerplate. The reason is to prevent possible duplicates.

For instance, if I'm writing an ES6 app with babel, I will already have included the polyfill. If your library also includes the polyfill, then I would get two.

One option to resolve this would be to create two builds for your library, which some folks may prefer to do. I'm not against multiple bundles, but in this situation I think it's unnecessary.

Another option is to leave a note in the README that recommends using the browser polyfill, if you aren't already including it.

**Comment by nicksrandall** [comment]
What I would prefer is to have the polyfill listed as a dependency of my project so that anybody using a dependency manager like bower or npm can bring it in with my project. Most bundlers are smart enough to only bring in duplicate dependencies once. 

However, there isn't a repo anywhere that has just the browser polyfill so I can't list it as a dependency. I know this is a issue for babel so I've  created my own repo for the time being until babel creates a stand alone package for the polyfill.

**Comment by nicksrandall** [comment]
P.S. @jmeas thanks the help and for this project!

**Comment by jmeas** [comment]
> I know this is a issue for babel so I've created my own repo for the time being until babel creates a stand alone package for the polyfill.

Alright, cool. Should we go ahead and close this issue, then?

> P.S. @jmeas thanks the help and for this project!

No problem, @nicksrandall ! I'm glad you find it helpful :)

**Comment by nicksrandall** [comment]
Yeah, I think this issue can be closed.
