### ISSUE TITLE
Should not be depending on "babel"

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel-library-boilerplate#178]
https://github.com/babel/babel-library-boilerplate/blob/master/package.json#L34

This is unnecessary as it's not used in the devDependencies. This package (vs. babel-core) includes all of the CLI tools and will install a bunch of stuff that takes really long to install for no reason.

**Comment by jmeas** [comment]
k. So, to be clear, **only** `babel-core` needs to be a `devDep`?

**Comment by thejameskyle** [comment]
Yeah, I think all that is needed for is `require('babel-core/register')`, tools like babelify already use `babel-core`.

**Comment by jmeas** [comment]
K cool.

**Comment by rickardjanson** [comment]
@thejameskyle @jmeas This suggestion can give issues. See my latest comment in this issue ticket: https://github.com/babel/babel-library-boilerplate/issues/175

Problem is that `babel` will rely on some `import` statements that are not covered by the `babel/core` if you want to convert the gulp-file to babel syntax as suggested in latest babel releases.

Next issue will be that Travis CI will scream about errors because it can't import files directly. E.g. 
`import jmeas from Babel` give at least me and some of my clients issues.

I\m not sure if the last issue are directly bound to this, but at least a workaround has to be

```
import Babel from Babel
const jmeas = Babel
```

**Comment by thejameskyle** [comment]
That doesn't make any sense to me but regardless this is the right thing to do and you should report upstream.

**Comment by rickardjanson** [comment]
@thejameskyle Agree this make no sense, and I just now triggered one of the errors so you can see yourself:

```
(function (exports, require, module, __filename, __dirname) { import gulp from
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:411:25)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
```
This is from Travis CI. How would you report this upstream_

**Comment by thejameskyle** [comment]
Working fine for me https://travis-ci.org/thejameskyle/backbone.service/builds/68263952

Please open a reproducible test case elsewhere

**Comment by rickardjanson** [comment]
@thejameskyle I will open an issue higher up for this one. 

Ofc. your solution will work. My point was if you follow this link: https://twitter.com/wesbos/status/608987962370424832 and convert your gulpfile to gulpfile-babel.js you will get the error I wrote earlier. And a bunch of other errors....

This because you remove the babel dependency.

**Comment by skyrpex** [comment]
@rickardjanson you must rename it to gulpfile.babel.js.

Gulp will look for babel-core first. If not exist, will look for babel.
